"""`proj init` — bootstrap a manifest from a workspace directory."""

from __future__ import annotations

from pathlib import Path

_TEMPLATE_HEADER = """\
# proj manifest — generated by `proj init`.
# Edit freely. Run `proj defaults` to see the bundled command/column defaults
# you can override here.

workspace:
  root: {root}

settings:
  # unknown_handling: include | warn | ignore
  unknown_handling: include

projects:
"""

_TEMPLATE_PROJECTS_EMPTY = """\
  # No subdirectories found in {root}.
  # Add entries below, e.g.:
  #   my-project:
  #     tags: [mine, library]
"""

_TEMPLATE_FOOTER = """\

# --- Examples (uncomment to use) ---
#
# columns:
#   has_dockerfile:
#     value-from: test -f Dockerfile && echo true || echo false
#     type: boolean
#
#   otp_version:
#     applies-to: lang_elixir
#     value-from: grep otp .tool-versions | sed 's/.*-otp-//'
#     type: text
#     cache: true
#
# commands:
#   fmt:
#     type: run
#     where: has_justfile
#     cmd: just fmt
#
#   biggest:
#     type: query
#     columns: [name, size, last_modified]
#     order_by: size desc
#     limit: 10
"""


def list_subdirectories(root: Path) -> list[str]:
    """Return sorted immediate subdirectory names of `root`, skipping hidden dirs."""
    if not root.exists() or not root.is_dir():
        return []
    names: list[str] = []
    for entry in root.iterdir():
        if not entry.is_dir():
            continue
        if entry.name.startswith("."):
            continue
        names.append(entry.name)
    names.sort()
    return names


def render_manifest(root: Path, project_names: list[str]) -> str:
    """Render the YAML manifest text for `proj init`."""
    lines = [_TEMPLATE_HEADER.format(root=root)]
    if not project_names:
        lines.append(_TEMPLATE_PROJECTS_EMPTY.format(root=root))
    else:
        for name in project_names:
            lines.append(f"  {name}:\n    tags: []\n")
    lines.append(_TEMPLATE_FOOTER)
    return "".join(lines)


def write_manifest(manifest_path: Path, content: str) -> None:
    """Write `content` to `manifest_path`, creating parent directories as needed."""
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(content)
